/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import conexion.conexion;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;

/**
 *
 * @author kelly
 */
public class Autos extends javax.swing.JFrame {

    int idAutoSeleccionado = 0; 
    /**
     * Creates new form Autos
     */
    public Autos() {
        initComponents();
        cargarTabla();
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnModi = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtMarca = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtDueños = new javax.swing.JTextField();
        txtKilo = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtInicio = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE AUTOS");

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel4.setText("Precio");

        jLabel5.setText("Estado");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModi.setText("Modificar");
        btnModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Usado" }));
        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel7.setText("Color");

        jLabel8.setText("Dueños");

        jLabel9.setText("Kilometraje");

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        txtDueños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDueñosActionPerformed(evt);
            }
        });

        txtKilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKiloActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtInicio.setText("Inicio");
        txtInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInicioActionPerformed(evt);
            }
        });

        jLabel6.setText("Stock");

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        jLabel10.setText("Buscar por Id");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(47, 47, 47)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel8))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKilo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDueños, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(btnModi)
                                .addGap(90, 90, 90)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(388, 388, 388))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6))
                            .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDueños, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKilo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnModi)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnBuscar))
                .addGap(30, 30, 30)
                .addComponent(txtInicio)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void btnModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiActionPerformed
 
        if (idAutoSeleccionado == 0) {
     
        JOptionPane.showMessageDialog(null, "Error: No has seleccionado ningún auto de la tabla.", "Campo no seleccionado", JOptionPane.ERROR_MESSAGE);
        } else {

        estadoEditando();
        txtMarca.requestFocus(); 
        }  
    }//GEN-LAST:event_btnModiActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    if (idAutoSeleccionado == 0) {
        JOptionPane.showMessageDialog(null, "Error: Selecciona un auto de la tabla para eliminarlo.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }


    int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas eliminar este auto permanentemente?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
   
            String url = "jdbc:mysql://localhost:3306/concesionaria?useSSL=false&allowPublicKeyRetrieval=true";
            Connection cn = DriverManager.getConnection(url, "root", "123");

            String sqlUsado = "DELETE FROM autousado WHERE idAuto = ?";
            PreparedStatement pstUsado = cn.prepareStatement(sqlUsado);
            pstUsado.setInt(1, idAutoSeleccionado);
            pstUsado.executeUpdate();


            String sqlAuto = "DELETE FROM autos WHERE idAuto = ?";
            PreparedStatement pstAuto = cn.prepareStatement(sqlAuto);
            pstAuto.setInt(1, idAutoSeleccionado);
            pstAuto.executeUpdate();

            JOptionPane.showMessageDialog(null, "El auto ha sido eliminado con éxito.");
            
            cargarTabla(); 
            inicio();      
            idAutoSeleccionado = 0; 

            txtMarca.setText("");
            txtModelo.setText("");
            txtColor.setText("");
            txtPrecio.setText("");
            txtStock.setText("");
            txtDueños.setText("");
            txtKilo.setText("");
            cbxEstado.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar: " + e.getMessage());
        }
    }    
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtDueñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDueñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDueñosActionPerformed

    private void txtKiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKiloActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {

        conexion cc = new conexion();
        Connection cn = cc.getConexion();
        
        String estadoAuto = cbxEstado.getSelectedItem().toString();

        if (idAutoSeleccionado == 0) {
            
            String sqlAutos = "INSERT INTO autos (marca, modelo, color, precio, estado, stock) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstAutos = cn.prepareStatement(sqlAutos, Statement.RETURN_GENERATED_KEYS);
            
            pstAutos.setString(1, txtMarca.getText().trim());
            pstAutos.setString(2, txtModelo.getText().trim());
            pstAutos.setString(3, txtColor.getText().trim());
            pstAutos.setString(4, txtPrecio.getText().trim());
            pstAutos.setString(5, estadoAuto);
            pstAutos.setString(6, txtStock.getText().trim());
            
            pstAutos.executeUpdate();
            
            ResultSet rs = pstAutos.getGeneratedKeys();
            if (rs.next()) {
                int idNuevo = rs.getInt(1); 
                if (estadoAuto.equalsIgnoreCase("Usado")) { 
                    String sqlUsado = "INSERT INTO autousado (idAuto, numDueños, kilometraje) VALUES (?, ?, ?)";
                    PreparedStatement pstUsado = cn.prepareStatement(sqlUsado);
                    pstUsado.setInt(1, idNuevo);
                    pstUsado.setString(2, txtDueños.getText().trim());
                    pstUsado.setString(3, txtKilo.getText().trim());
                    pstUsado.executeUpdate();
                }
            }
            JOptionPane.showMessageDialog(null, "¡Auto nuevo registrado con éxito!");

        } else {
            
            String sqlUpdate = "UPDATE autos SET marca=?, modelo=?, color=?, precio=?, estado=?, stock=? WHERE idAuto=?";
            PreparedStatement pstUpdate = cn.prepareStatement(sqlUpdate);
            
            pstUpdate.setString(1, txtMarca.getText().trim());
            pstUpdate.setString(2, txtModelo.getText().trim());
            pstUpdate.setString(3, txtColor.getText().trim());
            pstUpdate.setString(4, txtPrecio.getText().trim());
            pstUpdate.setString(5, estadoAuto);
            pstUpdate.setString(6, txtStock.getText().trim());
            pstUpdate.setInt(7, idAutoSeleccionado); // Usamos el ID atrapado
            
            pstUpdate.executeUpdate();
            String sqlBorrarUsado = "DELETE FROM autousado WHERE idAuto=?";
            PreparedStatement pstBorrar = cn.prepareStatement(sqlBorrarUsado);
            pstBorrar.setInt(1, idAutoSeleccionado);
            pstBorrar.executeUpdate();
            
            if (estadoAuto.equalsIgnoreCase("Usado")) {
                String sqlUsado = "INSERT INTO autousado (idAuto, numDueños, kilometraje) VALUES (?, ?, ?)";
                PreparedStatement pstUsado = cn.prepareStatement(sqlUsado);
                pstUsado.setInt(1, idAutoSeleccionado); 
                pstUsado.setString(2, txtDueños.getText().trim());
                pstUsado.setString(3, txtKilo.getText().trim());
                pstUsado.executeUpdate();
            }
            
            JOptionPane.showMessageDialog(null, "¡Auto actualizado con éxito!");
        }

        cargarTabla(); 
        txtMarca.setText("");
        txtModelo.setText("");
        txtColor.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtDueños.setText("");
        txtKilo.setText("");
        cbxEstado.setSelectedIndex(0);
        
        idAutoSeleccionado = 0; 
        inicio();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al guardar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        New();
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        inicio();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
       
    int fila = tabla.getSelectedRow();
    
    
    if (fila >= 0){

        idAutoSeleccionado = Integer.parseInt(tabla.getValueAt(fila, 0).toString());

        txtMarca.setText(tabla.getValueAt(fila, 1).toString());
        txtModelo.setText(tabla.getValueAt(fila, 2).toString());
        txtColor.setText(tabla.getValueAt(fila, 3).toString());
        txtPrecio.setText(tabla.getValueAt(fila, 4).toString());

        String estado = tabla.getValueAt(fila, 5).toString();
        

        if (estado.equalsIgnoreCase("Usado")) {
            
            cbxEstado.setSelectedItem("Usado"); 
            txtDueños.setEnabled(true);
            txtKilo.setEnabled(true);
            txtDueños.setText(tabla.getValueAt(fila, 6).toString());
            txtKilo.setText(tabla.getValueAt(fila, 7).toString());
            
        } else {
            
            cbxEstado.setSelectedItem("Nuevo");
            txtDueños.setEnabled(false);
            txtKilo.setEnabled(false);
            txtDueños.setText("");
            txtKilo.setText("");
            
        }

        txtStock.setText(tabla.getValueAt(fila, 8).toString());
 
        estadoSelec();
    } 
    }//GEN-LAST:event_tablaMouseClicked

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        String seleccion = cbxEstado.getSelectedItem().toString();

        if (seleccion.equalsIgnoreCase("Usado")) {
            txtDueños.setEnabled(true);
            txtKilo.setEnabled(true);
        }else {
            txtDueños.setEnabled(false);
            txtKilo.setEnabled(false);

            if (btnGuardar.isEnabled()) {
                txtDueños.setText("");
                txtKilo.setText("");
            }
        }
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    String idBuscado = txtBuscar.getText().trim();
        if (idBuscado.isEmpty()) {
        cargarTabla();
        return; 
    }

  javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };
    
    modelo.addColumn("id");
    modelo.addColumn("marca");
    modelo.addColumn("modelo");
    modelo.addColumn("color");
    modelo.addColumn("precio");
    modelo.addColumn("estado");
    modelo.addColumn("dueños");
    modelo.addColumn("kilometraje");
    modelo.addColumn("stock");

    try {
        conexion cc = new conexion();
        Connection cn = cc.getConexion();
String sql = "SELECT a.*, u.numDueños, u.kilometraje " +
                     "FROM autos a " +
                     "LEFT JOIN autousado u ON a.idAuto = u.idAuto " +
                     "WHERE a.idAuto = ?";

        java.sql.PreparedStatement pst = cn.prepareStatement(sql);
        pst.setInt(1, Integer.parseInt(idBuscado));

        java.sql.ResultSet rs = pst.executeQuery();

        boolean encontro = false;

        while (rs.next()) {
            encontro = true; 
            modelo.addRow(new Object[]{
                rs.getString("idAuto"),
                rs.getString("marca"),
                rs.getString("modelo"),
                rs.getString("color"),
                rs.getString("precio"),
                rs.getString("estado"),
                rs.getString("numDueños"),
                rs.getString("kilometraje"),
                rs.getString("stock")
            });
        }
  if (!encontro) {
            javax.swing.JOptionPane.showMessageDialog(null, "No se encontró ningún auto con el ID: " + idBuscado);
            txtBuscar.setText(""); 
            cargarTabla(); 
        } else {
            tabla.setModel(modelo); 
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Por favor, ingresa solo números para buscar por ID.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        txtBuscar.setText("");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error al buscar: " + e.getMessage());
    }    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicioActionPerformed
        // TODO add your handling code here:
        inicio VentanaNueva = new inicio();
        VentanaNueva.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autos().setVisible(true);
            }
        });
    }
    
    public void cargarTabla(){
        DefaultTableModel modelo = new DefaultTableModel() {
    @Override
    public boolean isCellEditable(int row, int column) {
     
        return false; 
    }
};
        modelo.addColumn("id");
        modelo.addColumn("marca");
        modelo.addColumn("modelo");
        modelo.addColumn("color");
        modelo.addColumn("precio");
        modelo.addColumn("estado");
        modelo.addColumn("dueños");
        modelo.addColumn("kilometraje");
        modelo.addColumn("stock");
        
        tabla.setModel(modelo);
        
         try {
            conexion cc = new conexion();
            Connection cn = cc.getConexion();
                String sql = "SELECT a.*, u.numDueños, u.kilometraje " +
                            "FROM autos a " +
                            "LEFT JOIN autousado u ON a.idAuto = u.idAuto";

                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
             while (rs.next()){
    
        modelo.addRow(new Object[]{
        rs.getString("idAuto"), 
        rs.getString("marca"),
        rs.getString("modelo"),
        rs.getString("color"),
        rs.getString("precio"),
        rs.getString("estado"),
        rs.getString("kilometraje"),
        rs.getString("numDueños"),
        rs.getString("stock")
                 });
             }
         } catch (Exception e){
             JOptionPane.showMessageDialog(null, "Error al mostrar"+ e.getMessage());
         }
        
    }
    
    
    
    private void inicio(){
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnModi.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        txtMarca.setEnabled(false);
        txtModelo.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtColor.setEnabled(false);
        txtStock.setEnabled(false);
        cbxEstado.setEnabled(false);
        txtKilo.setEnabled(false);
        txtDueños.setEnabled(false);
    }
    
    
    private void New(){
       
        txtMarca.setText("");
        txtModelo.setText("");
        txtColor.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtDueños.setText("");
        txtKilo.setText("");
        cbxEstado.setSelectedIndex(0); 
        idAutoSeleccionado = 0; 

            btnGuardar.setEnabled(true);
            btnCancelar.setEnabled(true);

            // Apagamos los que no sirven para crear
            btnNuevo.setEnabled(false);
            btnModi.setEnabled(false);
            btnEliminar.setEnabled(false);

        txtMarca.setEnabled(true);
        txtModelo.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtColor.setEnabled(true);
        txtStock.setEnabled(true);
        cbxEstado.setEnabled(true);

       
        cbxEstado.setSelectedIndex(0); 
        txtDueños.setEnabled(false);
        txtKilo.setEnabled(false);
    }
    
    public void estadoSelec(){
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(false);
        
        btnModi.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
        txtMarca.setEnabled(false);
        txtModelo.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtColor.setEnabled(false);
        txtStock.setEnabled(false);
        cbxEstado.setEnabled(false);
        txtDueños.setEnabled(false);
        txtKilo.setEnabled(false);
        
    }
    
    public void estadoEditando() {
  
    txtMarca.setEnabled(true);
    txtModelo.setEnabled(true);
    txtPrecio.setEnabled(true);
    txtColor.setEnabled(true);
    txtStock.setEnabled(true);
    cbxEstado.setEnabled(true);

    String estadoActual = cbxEstado.getSelectedItem().toString();
    if (estadoActual.equalsIgnoreCase("Usado")) {
        txtDueños.setEnabled(true);
        txtKilo.setEnabled(true);
    } else {
        txtDueños.setEnabled(false);
        txtKilo.setEnabled(false);
    }
    btnModi.setEnabled(false); 
    btnGuardar.setEnabled(true);  
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModi;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDueños;
    private javax.swing.JButton txtInicio;
    private javax.swing.JTextField txtKilo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
