/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kelly
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        cargartabla();
        inhabilitar();
    }
void habilitar(){
    btnCancelar.setEnabled(true);
    btnGuardar.setEnabled(true);
    btnNuevo.setEnabled(true);
    txtNombre.setEnabled(true);
    txtTelefono.setEnabled(true);
    txtApat.setEnabled(true);
    txtAmat.setEnabled(true);
    btnCambios.setEnabled(false);
    btnEditar.setEnabled(false);
    btnEliminar.setEnabled(false);
    }
    
    void inhabilitar(){
    btnGuardar.setEnabled(false);
    txtNombre.setEnabled(false);
    txtTelefono.setEnabled(false);
    txtApat.setEnabled(false);
    txtAmat.setEnabled(false);
    btnNuevo.setEnabled(true);
    btnCambios.setEnabled(false);
    btnEditar.setEnabled(false);
    btnCambios.setEnabled(false);
    btnEliminar.setEnabled(false);
    }
    
    void editar (){
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnCambios.setEnabled(true);
    }
    
    void cambios(){
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnCambios.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(true);
        
    }
    
 void vacio(){
 txtNombre.setText("");
 txtApat.setText("");
 txtAmat.setText("");
 txtTelefono.setText("");
 }
   
 
 void cargartabla(){
 conexion n = new conexion();
 Connection cn = n.getConexion();
 
 String [] titulos = {"Id", "Nombre", "Apellido Pat", "Apellido Mat", "Telefono"};
 String [] datosfila = new String [5];

 DefaultTableModel tabla = new DefaultTableModel(titulos, 0){
    @Override
    public boolean isCellEditable(int row, int column){
        return false;
    }
 };

 tablaCliente.setModel(tabla);


 tablaCliente.getTableHeader().setResizingAllowed(false); // no cambiar ancho
 tablaCliente.getTableHeader().setReorderingAllowed(false); // no mover columnas

 String sql = "SELECT * FROM cliente";
 try {
     Statement st = cn.createStatement();
     ResultSet rs = st.executeQuery(sql);
     while(rs.next()){
         datosfila[0] = rs.getString("idCliente");
         datosfila[1] = rs.getString("nombre");
         datosfila[2] = rs.getString("apPat");
         datosfila[3] = rs.getString("apMat");
         datosfila[4] = rs.getString("telefono");

         tabla.addRow(datosfila);
     }
 } catch (Exception e) {
     JOptionPane.showMessageDialog(null, e);
 }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApat = new javax.swing.JTextField();
        txtAmat = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Tel:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApatActionPerformed(evt);
            }
        });
        txtApat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApatKeyTyped(evt);
            }
        });

        txtAmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmatActionPerformed(evt);
            }
        });
        txtAmat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmatKeyTyped(evt);
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel6.setText("Selecciona un Cliente");

        jLabel8.setText("Buscar Cliente");

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCambios.setText("Guardar Edicion");
        btnCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApat, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(txtNombre)
                                    .addComponent(txtAmat)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(48, 48, 48)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar)
                    .addComponent(btnCambios))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnNuevo))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCambios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
inicio atras = new inicio();
        atras.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtApatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApatActionPerformed

    private void txtAmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmatActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
conexion sql = new conexion();
 Connection cn = sql.getConexion();
 if (txtNombre.getText().isEmpty() ||
    txtApat.getText().isEmpty() ||
    txtAmat.getText().isEmpty() ||
    txtTelefono.getText().isEmpty()) {

    JOptionPane.showMessageDialog(null, "Completa todos los campos");
    return;
}
   String apPat, apMat, nombre;
    apPat = txtApat.getText();
    apMat = txtAmat.getText();
    nombre = txtNombre.getText();
    String telefono;
    String c;
    c = txtTelefono.getText();
    telefono = txtTelefono.getText();
 
 String guardar = "INSERT INTO cliente(nombre, apPat, apMat, telefono) VALUES(?,?,?,?)";
        try {
            PreparedStatement datos = cn.prepareStatement(guardar);
            datos.setString(1,nombre);
             datos.setString(2,apPat);
              datos.setString(3,apMat);
                datos.setString(4,telefono);
                
                int n = datos.executeUpdate();
                if (n>0){
                    JOptionPane.showMessageDialog(null, "Los datos se guardaron correctamente");}
                cargartabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
            vacio();
inhabilitar();
cargartabla();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String idUsuario;
       idUsuario = txtbuscar.getText();
         if (idUsuario.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingresa un código de usuario válido");
        return; // casonohaynadajlsndfj
    }


       
     conexion n = new conexion();
     Connection cn = n.getConexion();
 
 String [] titulos = {"Id", "Nombre", "Apelldio Pat", "Apellido Mat", "Telefono"};
 String [] datosfila = new String [5];
 DefaultTableModel tabla = new DefaultTableModel(titulos, 0){
    @Override
    public boolean isCellEditable(int row, int column){
        return false;
    }
};
 tablaCliente.setModel(tabla);
 
String sql = "SELECT * FROM cliente WHERE idCliente = " + idUsuario;
     try {
         Statement st = cn.createStatement();
         ResultSet rs = st.executeQuery(sql);
         while(rs.next()){
         datosfila[0] = rs.getString("idCliente");
         datosfila[1] = rs.getString("nombre");
         datosfila[2] = rs.getString("apPat");
         datosfila[3] = rs.getString("apMat");
         datosfila[4] = rs.getString("telefono");
         
         tabla.addRow(datosfila);
         }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);
     }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
habilitar();
vacio();
// TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
inhabilitar();
        vacio();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    editar();
    txtNombre.setEnabled(true);
    txtApat.setEnabled(true);
    txtTelefono.setEnabled(true);
        int fila = tablaCliente.getSelectedRow();
       if (fila != -1) {
    String nombre = tablaCliente.getValueAt(fila, 1).toString();
    String apPat = tablaCliente.getValueAt(fila, 2).toString();
    String apMat = tablaCliente.getValueAt(fila, 3).toString();
    String telefono = tablaCliente.getValueAt(fila, 4).toString();

   
    
    txtApat.setText(apPat);
    txtAmat.setText(apMat);
    txtNombre.setText(nombre);
    txtTelefono.setText(telefono);
} else {
    JOptionPane.showMessageDialog(null, "Selecciona un usuario primero");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
int fila = tablaCliente.getSelectedRow();
if (fila == -1) {
    JOptionPane.showMessageDialog(null, "Selecciona un usuario primero");
    return;
}
String id = tablaCliente.getValueAt(fila, 0).toString();
try {
    Connection cn = new conexion().getConexion();
    String sql = "DELETE FROM cliente WHERE idCliente=?";
    PreparedStatement ps = cn.prepareStatement(sql);
    ps.setInt(1, Integer.parseInt(id));

    int filas = ps.executeUpdate();
    if (filas > 0) {
        JOptionPane.showMessageDialog(null, "Usuario eliminado correctamente");
        cargartabla();
    } else {
        JOptionPane.showMessageDialog(null, "No se encontró el usuario");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error al eliminar: " + e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiosActionPerformed
if (txtNombre.getText().isEmpty() ||
    txtApat.getText().isEmpty() ||
    txtAmat.getText().isEmpty() ||
    txtTelefono.getText().isEmpty()) {

    JOptionPane.showMessageDialog(null, "Completa todos los campos");
    return;
}
        try {
        Connection cn = new conexion().getConexion();
        String sql = "UPDATE cliente SET nombre=?, apPat=?, apMat=?, telefono=? WHERE idCliente=?";
        PreparedStatement ps = cn.prepareStatement(sql);

          int fila = tablaCliente.getSelectedRow();
          String id = tablaCliente.getValueAt(fila, 0).toString();
        
        ps.setString(1, txtNombre.getText());
        ps.setString(2, txtApat.getText());
        ps.setString(3, txtAmat.getText());
        ps.setString(4, txtTelefono.getText());
        ps.setInt(5, Integer.parseInt(id));

        int filas = ps.executeUpdate();
        if (filas > 0) {
            JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el usuario");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al actualizar: " + e.getMessage());
}
        vacio();
inhabilitar();
cargartabla();
        cargartabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiosActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
char c = evt.getKeyChar();

if (!Character.isLetter(c) && c != ' ') {
    evt.consume();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApatKeyTyped
char c = evt.getKeyChar();

if (!Character.isLetter(c) && c != ' ') {
    evt.consume();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApatKeyTyped

    private void txtAmatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmatKeyTyped
char c = evt.getKeyChar();

if (!Character.isLetter(c) && c != ' ') {
    evt.consume();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmatKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
char c = evt.getKeyChar();

if (!Character.isDigit(c)) {
    evt.consume();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
char c = evt.getKeyChar();

if (!Character.isDigit(c)) {
    evt.consume();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        // TODO add your handling code here:
        cambios();
    }//GEN-LAST:event_tablaClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambios;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField txtAmat;
    private javax.swing.JTextField txtApat;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
