package interfaz;
import conexion.conexion;
import javax.swing.table.DefaultTableModel; 
import java.sql.*;                                       
import javax.swing.JOptionPane;

/**
 *
 * @author itzrl
 */
public class Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form VentanaProveedores
     */
    public Proveedores() {
    initComponents();
    this.setLocationRelativeTo(null);
    mostrarDatos();
    inicio();

    
    txtEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            if (Character.isDigit(evt.getKeyChar())) {
                evt.consume();
            }
        }
    });

  
    txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            if (!Character.isDigit(evt.getKeyChar())) {
                evt.consume();
            }
        }
    });
}
  

    
public void mostrarDatos() {
   DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };
        modelo.addColumn("ID");
        modelo.addColumn("Empresa");
        modelo.addColumn("Teléfono");
        tblProveedores.setModel(modelo);

        String sql = "SELECT * FROM proveedores";
        String datos[] = new String[3];

        try {
            conexion cc = new conexion();
            Connection cn = cc.getConexion();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                datos[0] = rs.getString(1); 
                datos[1] = rs.getString(2); 
                datos[2] = rs.getString(3); 
                modelo.addRow(datos);
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al llenar tabla: " + e.getMessage());
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        txtEmpresa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GESTIÓN DE PROVEEDORES");

        jLabel2.setText("Nombre de la Empresa");

        jLabel3.setText("Teléfono");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnGuardar.setText("REGISTRAR PROVEEDOR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpresaKeyTyped(evt);
            }
        });

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Empresa", "Teléfono"
            }
        ));
        tblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedoresMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProveedoresMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedores);

        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(309, 309, 309))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnNuevo)
                        .addGap(67, 67, 67)
                        .addComponent(btnGuardar)
                        .addGap(53, 53, 53)
                        .addComponent(btnCancelar)
                        .addGap(44, 44, 44)
                        .addComponent(btnModificar)
                        .addGap(30, 30, 30)
                        .addComponent(btnGuardarCambios)
                        .addGap(37, 37, 37)
                        .addComponent(btnBorrar)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnGuardarCambios)
                            .addComponent(btnBorrar)
                            .addComponent(btnNuevo)
                            .addComponent(btnCancelar)
                            .addComponent(btnGuardar)))
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    if (!camposEstanLlenos()) {
        JOptionPane.showMessageDialog(this, "Error: Debe llenar todos los campos del proveedor.");
        return; 
    }
    String telefono = txtTelefono.getText().trim();

    if (!telefono.matches("[0-9]{10}")) {
        JOptionPane.showMessageDialog(this, "El teléfono debe tener exactamente 10 dígitos.");
        txtTelefono.requestFocus();
        return; 
    }

    try {
        conexion cc = new conexion();
        Connection cn = cc.getConexion();

        String sql = "INSERT INTO proveedores (nombre_empresa, telefono) VALUES (?, ?)";
        PreparedStatement ps = cn.prepareStatement(sql);

        ps.setString(1, txtEmpresa.getText().trim());
        ps.setString(2, telefono);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "¡Proveedor registrado con éxito!");

        mostrarDatos();   
        inicio(); 

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al guardar en la base: " + e.getMessage());
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        inicio VentanaNueva = new inicio();
        VentanaNueva.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

    estadoEditando();
    txtEmpresa.requestFocus();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
     
    if (!camposEstanLlenos()) {
        JOptionPane.showMessageDialog(this, "Error: No puede dejar campos vacíos al modificar.");
        return; 
    }

    String telefono = txtTelefono.getText().trim();

    if (!telefono.matches("[0-9]{10}")) {
        JOptionPane.showMessageDialog(this, "El teléfono debe tener exactamente 10 dígitos.");
        txtTelefono.requestFocus();
        return; 
    }
    try {
        
        int fila = tblProveedores.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un proveedor de la tabla.");
            return;
        }
        String id = tblProveedores.getValueAt(fila, 0).toString();

        conexion cc = new conexion();
        Connection cn = cc.getConexion();
        
        String sql = "UPDATE proveedores SET nombre_empresa=?, telefono=? WHERE idProveedor=?";
        PreparedStatement ps = cn.prepareStatement(sql);

        ps.setString(1, txtEmpresa.getText().trim());
        ps.setString(2, telefono);
        ps.setString(3, id);

        int resultado = ps.executeUpdate();
        if (resultado > 0) {
            JOptionPane.showMessageDialog(null, "Proveedor actualizado correctamente");
            mostrarDatos();
            inicio(); 
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al actualizar: " + e.getMessage());
    }  
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int fila = tblProveedores.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(null, "Seleccione el registro que desea eliminar");
        return;
    }

    int confirmar = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este proveedor?");
    
    if (confirmar == JOptionPane.YES_OPTION) {
        String id = tblProveedores.getValueAt(fila, 0).toString();
        
        try {
            conexion cc = new conexion();
            Connection cn = cc.getConexion();
            String sql = "DELETE FROM proveedores WHERE idProveedor=?";
            
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, id);
            
            pst.executeUpdate();
            mostrarDatos();
            limpiarCampos();
            JOptionPane.showMessageDialog(null, "Proveedor eliminado");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
       
    estadoNuevoRegistro();
    txtEmpresa.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedoresMouseClicked

    int fila = tblProveedores.getSelectedRow();
    
    if (fila >= 0) {

        txtEmpresa.setText(tblProveedores.getValueAt(fila, 1).toString());
        txtTelefono.setText(tblProveedores.getValueAt(fila, 2).toString());

        estadoRegistroSeleccionado();
    }
    }//GEN-LAST:event_tblProveedoresMouseClicked

    private void tblProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedoresMousePressed
        int fila = tblProveedores.getSelectedRow();
    if (fila >= 0) {
        txtEmpresa.setText(tblProveedores.getValueAt(fila, 1).toString());
        txtTelefono.setText(tblProveedores.getValueAt(fila, 2).toString());

        estadoRegistroSeleccionado();
        }
    }//GEN-LAST:event_tblProveedoresMousePressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

    txtEmpresa.setText("");
    txtTelefono.setText("");
    txtEmpresa.setEnabled(false);
    txtTelefono.setEnabled(false);

    tblProveedores.clearSelection();

    btnGuardar.setEnabled(true); 
    btnModificar.setEnabled(false);
    btnBorrar.setEnabled(false);
    btnGuardarCambios.setEnabled(false);

    btnCancelar.setEnabled(false);

    System.out.println("Acción cancelada y formulario reseteado.");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpresaKeyTyped
        char c = evt.getKeyChar();
       
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEmpresaKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c) && c != java.awt.event.KeyEvent.VK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });

    }
    private void limpiarCampos() {
    txtEmpresa.setText("");
    txtTelefono.setText("");
    }
    
    private void inicio() {
    limpiarCampos();
    txtEmpresa.setEnabled(false);
    txtTelefono.setEnabled(false);
    
    btnNuevo.setEnabled(true);
    btnGuardar.setEnabled(false);
    btnCancelar.setEnabled(false);
    btnModificar.setEnabled(false);
    btnGuardarCambios.setEnabled(false);
    btnBorrar.setEnabled(false);
}
    private void estadoNuevoRegistro() {
    txtEmpresa.setEnabled(true);
    txtTelefono.setEnabled(true);
    txtEmpresa.requestFocus();
    
    btnNuevo.setEnabled(false);
    btnCancelar.setEnabled(true);
    btnGuardar.setEnabled(true);
    btnGuardarCambios.setEnabled(false);
    btnModificar.setEnabled(false);
    btnBorrar.setEnabled(false);
}
 private void estadoRegistroSeleccionado() {
    txtEmpresa.setEnabled(false);
    txtTelefono.setEnabled(false);
    
    btnNuevo.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnGuardar.setEnabled(false);
    btnModificar.setEnabled(true);
    btnBorrar.setEnabled(true);
    btnGuardarCambios.setEnabled(false);
}   
    private void estadoEditando() {
    txtEmpresa.setEnabled(true);
    txtTelefono.setEnabled(true);
    txtEmpresa.requestFocus();
    
    btnNuevo.setEnabled(false);
    btnCancelar.setEnabled(true);
    btnGuardar.setEnabled(false);
    btnGuardarCambios.setEnabled(true);
    btnModificar.setEnabled(false);
    btnBorrar.setEnabled(false);
}
    
private boolean camposEstanLlenos() {
    if (txtEmpresa.getText().trim().isEmpty() || 
        txtTelefono.getText().trim().isEmpty()) {
        return false; 
    }
    return true; 
}   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
