/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import com.toedter.calendar.JDateChooser;
import conexion.conexion;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.*; 
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Toni
 */
public class Ventas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventas.class.getName());

    /**
     * Creates new form Ventass
     */
    public Ventas() {
        initComponents();
        mostrarVentas();
        bloquearCampos();
        llenarCombo();
        obtenerFecha(txtFecha);//fecha
        txtFecha.setDateFormatString("yyyy-MM-dd");
        txtFecha.setMaxSelectableDate(new java.util.Date());
        ((JTextField) txtFecha.getDateEditor().getUiComponent()).setEditable(false);
        
    }
    public void bloquearCampos() {
    txtMarca.setEditable(false);
    txtModelo.setEditable(false);
    txtPrecio.setEditable(false);
    txtEstado.setEditable(false);
    txtTotal.setEditable(false);
    txtNombreCliente.setEditable(false);
    txtTelefonoCliente.setEditable(false);
}
    
    //Fecha
    public String obtenerFecha(JDateChooser dateChooser) {
    if (dateChooser.getDate() == null) {
        return null;
    }

    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    return formato.format(dateChooser.getDate());
}
    
    private void llenarCombo(){
    try {
            conexion cc = new conexion();
            Connection cn = cc.getConexion();
            
       
            cmbCliente.removeAllItems();
            cmbCliente.addItem("Seleccione un cliente");
            ResultSet rsC = cn.createStatement().executeQuery("SELECT nombre FROM cliente");
            while (rsC.next()) cmbCliente.addItem(rsC.getString("nombre"));

            cmbAuto.removeAllItems();
            cmbAuto.addItem("Seleccione un auto");
            ResultSet rsA = cn.createStatement().executeQuery("SELECT CONCAT(marca, ' ', modelo) AS vehiculo FROM autos WHERE estado != 'vendido'");
            while (rsA.next()) cmbAuto.addItem(rsA.getString("vehiculo"));
            
            cn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar combos: " + e.getMessage());
        }
}
    
    private void limpiarCampos() {
    cmbCliente.setSelectedIndex(0);
    cmbAuto.setSelectedIndex(0);
    txtIdEmpleado.setText("");
    txtTotal.setText("");
}
    public void mostrarVentas() {
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("ID");
    modelo.addColumn("Fecha");
    modelo.addColumn("Cliente");
    modelo.addColumn("Empleado");
    modelo.addColumn("Auto");
    modelo.addColumn("Total");
    modelo.addColumn("Estado");

    tblVentas.setModel(modelo);

    String sql = "SELECT v.idVenta, v.fecha, " +
                 "c.nombre AS cliente, " +
                 "e.nombre AS empleado, " +
                 "CONCAT(a.marca, ' ', a.modelo) AS auto, " +
                 "v.totaldelaventa, " +
                 "a.estado " +
                 "FROM ventas v " +
                 "LEFT JOIN cliente c ON v.idCliente = c.idCliente " +
                 "LEFT JOIN empleados e ON v.idEmpleado = e.idEmpleado " +
                 "LEFT JOIN autos a ON v.idAuto = a.idAuto";

    try {
        conexion cc = new conexion();
        Connection cn = cc.getConexion();

        Statement st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idVenta"),
                rs.getString("fecha"),
                rs.getString("cliente"),
                rs.getString("empleado"),
                rs.getString("auto"),
                rs.getDouble("totaldelaventa"),
                rs.getString("estado")
            });
        }

        cn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al mostrar ventas: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        txtTotal = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cmbCliente = new javax.swing.JComboBox<>();
        cmbAuto = new javax.swing.JComboBox<>();
        txtFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Guardar venta");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVentas);

        txtTotal.addActionListener(this::txtTotalActionPerformed);

        txtNombreCliente.addActionListener(this::txtNombreClienteActionPerformed);

        btnLimpiar.setText("Limpiar campos");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jLabel1.setText("Cliente");

        jLabel2.setText("Auto");

        jLabel6.setText("Nombre");

        jLabel3.setText("Fecha");

        jLabel4.setText("Empleado");

        jLabel5.setText("Total");

        txtIdEmpleado.addActionListener(this::txtIdEmpleadoActionPerformed);

        jLabel7.setText("Telefono");

        txtTelefonoCliente.addActionListener(this::txtTelefonoClienteActionPerformed);

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        jLabel8.setText("Precio");

        txtEstado.addActionListener(this::txtEstadoActionPerformed);

        jLabel9.setText("Estado");

        txtModelo.addActionListener(this::txtModeloActionPerformed);

        jLabel10.setText("Modelo");

        txtMarca.addActionListener(this::txtMarcaActionPerformed);

        jLabel11.setText("Marca");

        jButton2.setText("Inicio");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCliente.addItemListener(this::cmbClienteItemStateChanged);

        cmbAuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAuto.addItemListener(this::cmbAutoItemStateChanged);
        cmbAuto.addActionListener(this::cmbAutoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(cmbAuto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                .addGap(0, 94, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(120, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(113, 113, 113)
                        .addComponent(btnLimpiar)
                        .addGap(191, 191, 191)))
                .addComponent(jButton2)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Validaciones iniciales
    if (cmbCliente.getSelectedIndex() == 0 || cmbAuto.getSelectedIndex() == 0 || txtIdEmpleado.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Selecciona cliente, auto e ingresa ID de empleado");
        return;
    }

    try {
        // Usamos tu clase de conexión a Azure
        conexion cc = new conexion();
        Connection cn = cc.getConexion();

        // id del Cliente
        PreparedStatement pstC = cn.prepareStatement("SELECT idCliente FROM cliente WHERE nombre = ?");
        pstC.setString(1, cmbCliente.getSelectedItem().toString());
        ResultSet rsC = pstC.executeQuery();

        if (!rsC.next()) {
            JOptionPane.showMessageDialog(null, "Cliente no encontrado");
            return;
        }
        int idCliente = rsC.getInt("idCliente");

        // id auto
        PreparedStatement pstA = cn.prepareStatement("SELECT idAuto FROM autos WHERE CONCAT(marca, ' ', modelo) = ?");
        pstA.setString(1, cmbAuto.getSelectedItem().toString());
        ResultSet rsA = pstA.executeQuery();

        if (!rsA.next()) {
            JOptionPane.showMessageDialog(null, "Auto no encontrado");
            return;
        }
        int idAuto = rsA.getInt("idAuto");

        // venta a azure
        PreparedStatement pstVenta = cn.prepareStatement(
            "INSERT INTO ventas (fecha, totaldelaventa, idEmpleado, idCliente, idAuto, tipPag) VALUES (?,?,?,?,?,?)"
        );

       
        java.sql.Date fecha = new java.sql.Date(txtFecha.getDate().getTime());

        pstVenta.setDate(1, fecha);
        pstVenta.setDouble(2, Double.parseDouble(txtTotal.getText()));
        pstVenta.setInt(3, Integer.parseInt(txtIdEmpleado.getText()));
        pstVenta.setInt(4, idCliente);
        pstVenta.setInt(5, idAuto);
        pstVenta.setString(6, "Liquidacion");

        pstVenta.executeUpdate();

        // eliminar
        PreparedStatement pstDelete = cn.prepareStatement("DELETE FROM autos WHERE idAuto = ?");
        pstDelete.setInt(1, idAuto);
        pstDelete.executeUpdate();

        JOptionPane.showMessageDialog(null, "Venta registrada con éxito y auto eliminado del inventario");

        // Llimpiar
        pstC.close();
        pstA.close();
        pstVenta.close();
        pstDelete.close();
        
       
        llenarCombo();    
        mostrarVentas();  
        limpiarCampos();

        cn.close(); // 

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Asegúrate de que el Total y el ID de Empleado sean números");
    } catch (SQLException e) {
        
        JOptionPane.showMessageDialog(null, "Error SQL en Azure: " + e.getMessage());
    } catch (NullPointerException e) {
        JOptionPane.showMessageDialog(null, "Error: Selecciona una fecha válida");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentasMouseClicked

    }//GEN-LAST:event_tblVentasMouseClicked

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpleadoActionPerformed

    private void txtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoClienteActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        inicio VentanaNueva = new inicio();
        VentanaNueva.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClienteItemStateChanged
        // TODO add your handling code here:
        // Solo actuamos cuando el usuario SELECCIONA una opción (evita que se ejecute dos veces)
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        
        String nombreSeleccionado = cmbCliente.getSelectedItem().toString();

       
        if (nombreSeleccionado.equals("Seleccione un cliente")) {
            txtNombreCliente.setText("");
            txtTelefonoCliente.setText("");
            return;
        }

        try {
            conexion cc = new conexion();
            Connection cn = cc.getConexion();

            
            PreparedStatement pst = cn.prepareStatement(
                "SELECT nombre, telefono FROM cliente WHERE nombre = ?"
            );

            pst.setString(1, nombreSeleccionado);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
             
                txtNombreCliente.setText(rs.getString("nombre"));
                txtTelefonoCliente.setText(rs.getString("telefono"));
            } else {
                txtNombreCliente.setText("");
                txtTelefonoCliente.setText("");
            }
            
            cn.close(); 

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener datos del cliente: " + e);
        }
    }
        
    }//GEN-LAST:event_cmbClienteItemStateChanged

    private void cmbAutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAutoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
    
    String autoSeleccionado = cmbAuto.getSelectedItem().toString();

    if (autoSeleccionado.equals("Seleccione un auto")) {
        txtMarca.setText("");
        txtModelo.setText("");
        txtPrecio.setText("");
        txtEstado.setText("");
        txtTotal.setText("");
        return;
    }

    try {
        conexion cc = new conexion();
        Connection cn = cc.getConexion();

        PreparedStatement pst = cn.prepareStatement(
            "SELECT marca, modelo, precio, estado FROM autos WHERE CONCAT(marca, ' ', modelo) = ?"
        );

        pst.setString(1, autoSeleccionado);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String estado = rs.getString("estado");
            double precioOriginal = rs.getDouble("precio");
            double totalFinal = precioOriginal;

            txtMarca.setText(rs.getString("marca"));
            txtModelo.setText(rs.getString("modelo"));
            txtEstado.setText(estado);

            if (estado.equalsIgnoreCase("vendido")) {
                JOptionPane.showMessageDialog(null, "Este auto ya está vendido ⚠️");
                txtPrecio.setText("");
                txtTotal.setText("");
                return;
            }

            if (estado.equalsIgnoreCase("usado")) {
                totalFinal = precioOriginal * 0.90; // 10% descuento
                JOptionPane.showMessageDialog(null, "Auto usado: 10% de descuento aplicado ");
            }

            txtPrecio.setText(String.valueOf(precioOriginal));
            txtTotal.setText(String.valueOf(totalFinal));

            txtTotal.setEditable(false);
            txtPrecio.setEditable(false);
        }

        cn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al obtener datos del auto: " + e);
    }
}

    }//GEN-LAST:event_cmbAutoItemStateChanged

    private void cmbAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbAuto;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtEstado;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}

